name: Web Scraping

# 定时任务：每天 UTC 时间 8 点运行
# 定时任务：每天 UTC 时间 0 点运行（即北京时间上午 8 点）
on:
  # schedule:
    # - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp aiofiles pyppeteer beautifulsoup4  # 安装异步所需的库

    - name: Run Scraper
      run: |
        python main.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Commit changes
      run: |
        git config --global user.name "mai19950"
        git config --global user.email "underdog-95@outlook.com"
        git add .
        # 检查是否有更改
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Update scraped content for $(date +'%Y-%m-%d')"
          git pull --rebase origin main
          git push origin main --force
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
